# LS
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# GIT
alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gst='git status'
alias gl='git log'
alias glp1='git log -1 -p'
alias glp2='git log -2 -p'
alias glp3='git log -3 -p'
alias glp4='git log -4 -p'
alias glp5='git log -5 -p'
alias gl1='git log -1'
alias gl2='git log -2'
alias gl3='git log -3'
alias gl4='git log -4'
alias gl5='git log -5'
alias gt="git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'' %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias gshs='git show -s'
alias gsh='git show'
alias gf='git fetch'
alias gm='git merge'
alias gmoi='merge origin/integration'
alias gpl='git pull'
alias gpoi='git pull origin integration'
alias gco='git checkout'
alias gcoi='git checkout origin/integration'
alias gcot='git checkout -t'
alias gc='git commit'
alias gca='git commit --amend'
alias gp='git push'
alias gpu='git push --set-upstream origin'
alias grh='git reset HEAD --'
alias gb='git branch'
alias gbc='git branch | grep -v "master" | grep -v ^* | xargs git branch -D'
alias gcfgl='git config --global --list'
alias gcfge='git config --global --edit'
alias gcfg='git config --global'
alias gcfe='git config --edit'
alias gcf='git config'
alias gdt='git difftool --dir-diff'
alias gd='git diff'
alias gmt='git mergetool'
